services:
  bastion:
    image: ${DOCKER_IMAGE:-ghcr.io/sdip15fa/bastion:main}
    container_name: bastion
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - ${BASTION_API_PORT}:${BASTION_API_PORT}
    tty: true
    restart: always
    environment:
      BOT_ID: ${BOT_ID}
      BOT_TOKEN: ${BOT_TOKEN}
      OWNER_ID: ${OWNER_ID}
      UNSAFE_MODE: ${UNSAFE_MODE}
      BASTION_MUSIC_ACTIVITY: ${BASTION_MUSIC_ACTIVITY}
      BASTION_RELAY_DMS: ${BASTION_RELAY_DMS}
      BASTION_API_PORT: ${BASTION_API_PORT}
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@bastion-mongo:${MONGO_PORT:-27017}
    depends_on:
      - bastion-mongo
    networks:
      - bastion
  bastion-mongo:
    container_name: bastion-mongo
    image: mongo:latest
    tty: true
    command: mongod --auth --port=${MONGO_PORT:-27017} --bind_ip_all
    restart: always
    ports:
      - ${MONGO_PORT:-27017}:${MONGO_PORT:-27017}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-bastion}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
      MONGO_INITDB_DATABASE: bastion
    networks:
      - bastion
    volumes:
      - ./data:/data/db
networks:
  bastion:
    driver: bridge

