services:
  bastion:
    image: ${DOCKER_IMAGE:-ghcr.io/TheBastionBot/Bastion:main}
    container_name: bastion
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:${PORT}
    tty: true
    restart: always
    volumes:
      - ./settings.yaml:/app/settings.yaml
    depends_on:
      - bastion-mongo
    networks:
      - bastion
  bastion-mongo:
    container_name: bastion-mongo
    image: mongo:latest
    tty: true
    command: mongod --auth --port=${MONGO_PORT:-27017} --bind_ip_all
    restart: always
    ports:
      - ${MONGO_PORT:-27017}:${MONGO_PORT:-27017}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-bastion}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
      MONGO_INITDB_DATABASE: bastion
    networks:
      - bastion
    volumes:
      - ./data:/data/db
networks:
  bastion:
    driver: bridge

